### ISSUE TITLE
Create OHW24 branch for 2024 tutorials

### ISSUE THREAD

**Issue by cpsarason** [oceanhackweek/ohw-tutorials#119]
By comparison to previous years, it looks like we need to have a OHW24 branch to update this repo and make it easy to scheduel and manage our tutorials for 2024.

**Comment by ocefpaf** [comment]
Done! All PRs should point to it:

https://github.com/oceanhackweek/ohw-tutorials/tree/OHW24

We can add a skeleton directory structure to help folks land their notebooks in the right place.
