### ISSUE TITLE
yodapy for OHW20?

### ISSUE THREAD

**Issue by emiliom** [oceanhackweek/ohw-tutorials#19]
Hey @lsetiawan ! OceanHackWeek starts on Monday; actually, it sort-of has started already, as we had two "pre-hackweek" sessions on Thu & Fri.

Anyway. We want to point people to useful resources and packages. We have a [conda environment file](https://github.com/oceanhackweek/ohw20-tutorials/blob/master/environment.yml). I was thinking it'd be good to including [yodapy](https://github.com/cormorack/yodapy), but wanted to check with you first:
- Would you have any concerns about us including it? The last yodapy release was a year ago, and you had a few other commits last Fall. I wouldn't call that inactive, so I'd guess it's in good shape!
- I assume the [conda-forge package](https://anaconda.org/conda-forge/yodapy) is "good"? It's not mentioned in the repo README 

If we do go ahead and include it, the generic jupyter notebook example in the repo is two years old. Can you check if it still works?

FYI, we (Sebastian Alvis) have set up a dedicated JupyterHub for OHW: https://ocean.hackweek.io. (The intro text in the login page needs to be updated)

Thanks!

**Comment by ocefpaf** [comment]
@emiliom do you need yodapy for OHW22? If not, can we close this one?
(I'm doing some issue clean-ups)

**Comment by emiliom** [comment]
Let's close it. @leewujung and I briefly talked about doing something with OOI data in the NW satellite, but we haven't discussed it recently. If we decide there's a need for yodapy or other OOI-related package, let's just open a new issue.
