### ISSUE TITLE
xarray.open_zarr not working on the hub

### ISSUE THREAD

**Issue by emiliom** [oceanhackweek/ohw-tutorials#20]
From @cgentemann :
> In my tutorial, I want to compare accessing netcdf versus Zarr on S3.  I created s3, make public, uploaded the zarr store, but xr.open_zarr is giving me an error (that it didn't give me when it was local to the jupyter hub).  If anyone is good at s3 etc. would you mind trouble shooting this with me?

There's no reason it shouldn't work on the hub if it works with a local environment created with the [environment.yml file in this repo](https://github.com/oceanhackweek/ohw20-tutorials/blob/master/environment.yml). @cgentemann please confirm that it works locally with such a conda environment. If it's not working with that env, could you post the exact example (notebook or code snipped) here?

**Comment by cgentemann** [comment]
Sorry, my slack question wasn't clear.  xr.open_zarr works on the Hub, I'm having trouble with S3 permissions on my personal account.

**Comment by emiliom** [comment]
Ok. Do you have configurations in you personal `~/.aws/credentials` file that you need to replicate in your Hub space?

Pinging @amanda-tan, @salvis2, @leewujung; hopefully they can help you figure it out.

**Comment by ocefpaf** [comment]
Closing this as stale. We should figure out AWS credentials for the next tutorial!
