### ISSUE TITLE
SOS and gliders in ohw20-tutorials/01-Data-Access

### ISSUE THREAD

**Issue by emiliom** [oceanhackweek/ohw-tutorials#25]
@ocefpaf in https://github.com/oceanhackweek/ohw20-tutorials/blob/master/01-Data-Access/00-DataAccess.ipynb I suggest you spend as little time as possible on SOS. IOOS is deprecating it, and I'm not aware of any other major marine data systems that provides SOS as the primary data access service.

Also, it'd be really nice if one of your Glider DAC query example could yield OOI gliders, as we did last year at OHW19: https://github.com/oceanhackweek/ohw19-tutorial-data-access-viz/blob/master/04.2-AUVs-GliderDAC_ERDDAP.ipynb

I know you can't really change anything at this point, but still wanted to mention it :slightly_smiling_face:

**Comment by ocefpaf** [comment]
There is an exercise on OOI glider and I cannot show both.

Also, there is still data that only exists in the SOS form. I start with ERDDAP and end with that to should the most interesting, and where we are going, first and the deprecated later. Removing it entirely at this point would also remove the chunk of data that is not available on ERDDAP yet.

**Comment by abkfenris** [comment]
How about having a living tutorials repo, and either tag or branch for each year?

**Comment by ocefpaf** [comment]
That is the goal. This was probably the last year we used year prefixes. We already implemented that in a few places, tutorials are next!

**Comment by ocefpaf** [comment]
Closing this one. We are preparing for OHW and we will update all the notebooks here.
