### ISSUE TITLE
Strategy for tutorials

### ISSUE THREAD

**Issue by ocefpaf** [oceanhackweek/ohw-tutorials#37]
This is a suggestion and open to discussion. Here is what I believe we could do starting from 2020/2021

- rename this repo to ohw-tutorials
- branch of master into 2020 and 2021
- freeze the 2020 branch (we can get releases and DOI for that but I would no go there right now)
- start working on 2021 based on previous years notebooks and environment

Pinging @emiliom, @leewujung, @SeascapeScience, @abarciauskas-bgse, @cathmmitchell, @cgentemann, @dcherian, @leportella and @MathewBiddle  (we should create a tutorials team to make pinging easier!)

**Comment by dcherian** [comment]
Do we need branches or would it be enough to tag things?

**Comment by ocefpaf** [comment]
> Do we need branches or would it be enough to tag things?

I kind of prefer branches to organize things but I'm opened to ideas.

**Comment by emiliom** [comment]
> we should create a tutorials team to make pinging easier!

@ocefpaf you have admin rights to the github org. Feel free to create a team!


>> Do we need branches or would it be enough to tag things?
>
> I kind of prefer branches to organize things but I'm opened to ideas.

A branch lets people use the content the same way they would use the `master` branch (browse, clone, etc), so I like that. A tag doesn't, right?
