### ISSUE TITLE
Machine Learning tutorials / resources in the Earth Sciences

### ISSUE THREAD

**Issue by emiliom** [oceanhackweek/ohw-tutorials#5]
I won't have any role on the machine learning tutorial, but I wanted to share these recent ML resources I've run into, b/c they're designed specifically for an Earth Science context:

- [NCAR Artificial Intelligence for Earth System Science (AI4ESS) Summer School](https://www2.cisl.ucar.edu/events/summer-school/ai4ess/2020/artificial-intelligence-earth-system-science-ai4ess-summer-school). Took place in June, and I heard good things about it. Their materials are openly available
- [ML Classification and Regression tutorials from the ESIP ML cluster](https://github.com/geo-yrao/esip-ml-tutorials). Presented this month at the ESIP summer meeting. In R & Python
- [ICESat-2 Hackweek 2020, Introduction to Machine Learning and Remote Sensing](https://github.com/ICESAT-2HackWeek/Machine-Learning)
- [Workshop on Knowledge Guided Machine Learning (KGML), A Framework for Accelerating Scientific Discovery](https://sites.google.com/umn.edu/kgml/workshop). Online workshop, August 18-20 (Registration deadline: Aug 11). Great time frame for OHW participants. Heck, I may try to attend myself! 3 of the 4 science domains used in the sample applications (aquatic ecodynamics, climate and weather, hydrology, and translational biology) are in the earth sciences

If nothing else, compiling these links here will be useful to me :wink:

cc @valentina-s @leportella @leewujung 

Update, for completeness: https://github.com/oceanhackweek/ohw19-tutorial-machine-learning

**Comment by valentina-s** [comment]
Thanks @emiliom! Those all are great resources. Regarding the workshop, maybe we can announce it once participants get on slack (maybe at random channel), so they register if interested?

**Comment by emiliom** [comment]
> Regarding the workshop, maybe we can announce it once participants get on slack (maybe at random channel), so they register if interested?

Yeah, I agree.

**Comment by ocefpaf** [comment]
@valentina-s BTW, we are aggregating the tutorials in this repository. Once you have your slides please send a PR here to the `06-Machine-Learning` folder.

**Comment by emiliom** [comment]
The upcoming August issue of AGU Eos is very relevant:
- [The Rise of Machine Learning. Our August issue explores the way we process, analyze, and clearly present the massive amounts of information collected by scientists today](https://eos.org/agu-news/the-rise-of-machine-learning)
- https://eos.org/wp-content/uploads/2020/07/EOS_AUG20.pdf

Not for tutorials per se, but for wider context in the earth (and planetary) sciences.

**Comment by ocefpaf** [comment]
Let's close this one for now. We could use a "extra resources" page in our website though.
