### ISSUE TITLE
Fix spelling errors reported by Git pre-commit

### ISSUE THREAD

**Issue by abarciauskas-bgse** [oceanhackweek/ohw-tutorials#52]
There are some spelling errors in the xarray tutorial that are causing pre-commit CI to ❌  https://results.pre-commit.ci/run/github/248258492/1627960742.W9_ApcaRSGKk6ncjdFg23Q

For example:
```
Xarray/xarray-oceanhackweek21.ipynb:10263: FO ==> OF, FOR
Xarray/xarray-oceanhackweek21.ipynb:10263: nD ==> and, 2nd
Xarray/xarray-oceanhackweek21.ipynb:10263: BA ==> BY, BE
Xarray/xarray-oceanhackweek21.ipynb:10349: nD ==> and, 2nd
Xarray/xarray-oceanhackweek21.ipynb:13443: nd ==> and, 2nd
Xarray/xarray-oceanhackweek21.ipynb:13621: trys ==> tries
Xarray/xarray-oceanhackweek21.ipynb:13621: trys ==> tries
Xarray/xarray-oceanhackweek21.ipynb:13621: trys ==> tries
Xarray/xarray-oceanhackweek21.ipynb:13621: trys ==> tries
```

**Comment by ocefpaf** [comment]
Just ignore those for now. I'm trying to "fix" the pre-commit to ignore the output cells, those are all false positive pulled from the base64 strings.

**Comment by ocefpaf** [comment]
Closing this one for now. While codespell is very helpful it can be annoying on notebooks. I'll either disable it in the future or find an alternative to ignore notebook outputs. (Maybe we should not be commiting notebook outputs but that is another discussion.)
