### ISSUE TITLE
2022 planning

### ISSUE THREAD

**Issue by ocefpaf** [oceanhackweek/ohw-tutorials#67]
Let's kick off the discussion for the OHW22 tutorial planning! Here are the items we (or maybe I) need to discussion in today's meeting

- [x] List of instructors
- [x] R/Python balance
- [x] Schedule
- [x] Topics:
  - Data Access (Filipe:heavy_check_mark:/Ben Tupper/Emilio?)
  - Xarray/Dask (Deepak:heavy_check_mark:)
  - Visualization (Ben Tupper/@lidefi87?)
  - Machine Learning (Filipe:heavy_check_mark:/Valentina?)
  - Reproducible Science (Joseph/Nick?)
  - Mental Health (@abkfenris) (in-person only):heavy_check_mark:
 
Pinging @dgumustel, @leewujung, @gmanuch, @lidefi87 and @cathmmitchell.

Meeting notes: https://docs.google.com/document/d/1v5QX7V5WUDMWyyWNRL348BthhAloUgVZIoZ0NNM9EVM/edit#heading=h.6ijbvy87orxq

**Comment by ocefpaf** [comment]
> 1. A walk-through on how to make a package in R

That is something we could add to the Reproducible Science tutorial. We had/have something on Python there already.

The participants stated interests seems to be all over the place to due to wide net we used! I'll try to see if we can narrow it down a bit.

**Comment by ONR-MURI** [comment]
Hi

**Comment by ocefpaf** [comment]
Actionable items
 - [ ] Create a page with a of resources based on previous tutorials

**Comment by lidefi87** [comment]
> I'm sorry I can't make today... But something that came out of yesterday's meeting was each satellite organizers were to look through they're participants stated interests to see if there was anything obvious regarding tutorial suggestions.
> 
> I have spoken a little with Ben Tupper regarding OHW. Couple topics that came up (but might be more appropriate for projects):
> 
> 1. A walk-through on how to make a package in R
> 2. He (& some of Nick R's team) have been working on a package recently to add covariate data (from different data sources) to tabular data (https://github.com/BigelowLab/xyzt). At the moment, I think they have a separate package that gets GHRSST and is used in combination with `xyzt`, but I think their vision is to build it out more to integrate with other data sources.
> 
> Thoughts on those topics?

One request I received from an Australian participant was a tutorial on parallelisation using Dask. I would also be interested in this as I still struggle with this package and I find their documentation at times is not easy to follow.

**Comment by lidefi87** [comment]
> Let's kick off the discussion for the OHW22 tutorial planning! Here are the items we (or maybe I) need to discussion in today's meeting
> 
> * [ ]  List of instructors
> * [ ]  R/Python balance
> * [ ]  Schedule
> * [ ]  Topics:
>   
>   * Data Access (Filipe/Ben Tupper?)
>   * Visualization (Ben Tupper?)
>   * Machine Learning (Filipe?)
>   * Reproducible Science (Joseph?)
>   * Mental Health (@abkfenris) (in-person only)
> 
> Pinging @dgumustel, @leewujung, @ONR-MURI, @@lidefi87 and @cathmmitchell.

I would be happy to contribute with a tutorial of basic data manipulation and visualisation in R if needed.

**Comment by ocefpaf** [comment]
> One request I received from an Australian participant was a tutorial on parallelisation using Dask. 

I asked @dcherian and he is OK repeating the xarray tutorial. Maybe that is something he can address in his xarray tutorial, or we may schedule some extra  time just for that.

**Comment by abkfenris** [comment]
One of my coworkers made a cool visualization that combined Python for data access and reshaping, and R for visualization that could be a good series of tutorials:

> A little late for [#showyourstripes](https://twitter.com/hashtag/showyourstripes?src=hashtag_click) day, but I was inspired to follow [@CedScherer](https://twitter.com/CedScherer)'s visualization of warming in Europe with an ocean version using global large marine ecosystems. Temperature data is [#NOAA](https://twitter.com/hashtag/NOAA?src=hashtag_click) OISSTv2, processing done with [#xarray](https://twitter.com/hashtag/xarray?src=hashtag_click), plotting with [#ggplot](https://twitter.com/hashtag/ggplot?src=hashtag_click) & [#rstats](https://twitter.com/hashtag/rstats?src=hashtag_click).
>
> ![](https://pbs.twimg.com/media/FXACqiYXwAAirBz?format=png&name=large)
>
https://twitter.com/KemberlingAdam/status/1544738077612064773

He was signed up as a participant last year, but I believe got whacked by covid just beforehand and wasn't able to follow along with the event. I'm trying to figure out how interested he would be in running a tutorial himself.

I think there are a bunch of natural ways to break the problem down to limit computational time, and still make it possible for people to jump in later and catch up. I think there are some possibilities that also lead towards getting folks to explore (visualizations, different regions/time ranges, data sources...)

**Comment by dcherian** [comment]
> I asked @dcherian and he is OK repeating the xarray tutorial. Maybe that is something he can address in his xarray tutorial, or we may schedule some extra time just for that.

IMO dask should be a separate thing. It's orthogonal to everything in the 45 minute xarray tutorial. I'm happy to do it if there's time for an extra 45minute tutorial

**Comment by ocefpaf** [comment]
> I'm happy to do it if there's time for an extra 45minute tutorial

Thanks. We need to take that into account  for scheduling the tutorials. I'll keep you posted as soon as we have something more solid. Please watch this space.

**Comment by lidefi87** [comment]
I agree with @dcherian, I think dask requires a more in-depth session if possible.

**Comment by emiliom** [comment]
For mental health tutorial, @abkfenris says Wednesday would be best

**Comment by abkfenris** [comment]
And for the mental health tutorial, its open to anyone synchronous during the GVE slot, but it will not be recorded.

**Comment by ocefpaf** [comment]
> I agree with @dcherian, I think dask requires a more in-depth session if possible.

@dcherian our jupyterhub is live. Please let us know if you want to test it out for the xarray/dask tutorial.

**Comment by dcherian** [comment]
> . Please let us know if you want to test it out for the xarray/dask tutorial.

Yes please. Though I'll get it to later.

Do you all have a list of learning goals for the dask tutorial? Or another way, what would it be good to cover given some of the projects they might work on?
