### ISSUE TITLE
Schedule for OHW22

### ISSUE THREAD

**Issue by ocefpaf** [oceanhackweek/ohw-tutorials#68]
@leewujung I'm pasting the tentative schedule here for visibility Most of the instructors do not have access to the admin repo.

---

Latest schedule + tutorials from the last 3 meetings:
- All time below: Pacific Daylight Time (UTC-7)
- We almost have all speakers confirmed

Thing to raise to Steering committee:
- We prefer/default to live delivery, but they can choose to give us pre-recorded videos, or have videos as back up
  - People talk differently in recording and live scenarios
  - More engaging
- Make sure satellite arrange for how satellite will connect to Zoom tutorials (on a big screen or individually)

-------------------------

### Monday
- 1100-1130: Introduction + Code of Conduct
- 1130-1145: Break
- 1145-1245: Xarray (Deepak Cherian)
- 1245-1300: Break
- 1300-1400: Project brainstorming, in-person and also on google doc

### Tuesday
- 1100-1115: Satellite report out
- 1115-1120: Break
- 1120-1200: Data access in Python (Filipe Fernandes)
- 1200-1215: Break
- 1215-1300: Data access in R (Johnathan Evanilla)
- 1300-1315: Break
- 1315-1400: Machine learning introduction (Valentina Staneva)

### Wednesday
- 1100-1115: Project team report out
- 1115-1200: Data visualization in R (Camille Ross)
- 1200-1215: Break
- 1215-1300: Data visualization in Python (Derya Gumustel)
- 1300-1315: Break
- 1315-1400: Satellite-dependent, one of: Mental health discussions (Alex Kerney) / Project work / Code of conduct reflection

### Thursday
- 1100-1145: Machine learning applications (Filipe Fernandes)
- 11145-1200: Break
- 1200-1245: Best practices for reproducible research (Nick Record)
- 1245-1300: Break
- 1300-1400: Dask (Deepak Cherian)

### Friday
- 1100-1200: Project final touch
- 1200-1400: Project presentations (max 16 projects, based on 5 mins per presentation)

-------------------------

### Optional tutorials
- Pre-recorded tutorials: Satellite can optionally decide if they want to watch these together
  - Cloud setup, access, computation (Amanda Tan)
  - Environment management (Filipe Fernandes)
- Notebook resources:
  - UW undergrad program: xarray tutorial using sea surface temperature, basic machine learning

**Comment by ocefpaf** [comment]
Pinging @valentina-s, @dcherian, @btupper, and @dgumustel for visibilty.

**Comment by abkfenris** [comment]
Note, the ML intro was bumped to the first slot Thursday sliding everything back a slot, and Mental health is last slot on Wednesday.

**Comment by cathmmitchell** [comment]
I spoke with @btupper, @jevanilla (Johnathan Evanilla) and @chross22 (Camille Ross) yesterday. @jevanilla is giving the R data access tutorial and @chross22 is giving the R data viz tutorial. I updated the Google Sheet schedule which is linked to the website

**Comment by ocefpaf** [comment]
> Note, the ML intro was bumped to the first slot Thursday sliding everything back a slot, and Mental health is last slot on Wednesday.

@abkfenris we shuffled things a bit the Mental Health (MH) is on the last slot Wednesday now.
@valentina-s your ML overview is the last slot on Tuesday.
@dcherian we move the dask demostration to the last slot on Thursday.

The reasons for this change are: MH needs to hit folks at the middle of the week to where they ice was already broke but they are not too burnout yet. The ML learning should be ASAP but xarray-dask is mostly a demonstration to show a tool that students need to know when they need to scale things. We don't really want them using that for OHW projects b/c we cannot afford everybody processing terabytes of data as an exercise.

**Comment by ocefpaf** [comment]
@cathmmitchell I need the GitHub handle for Johnathan Evanilla to add him to the instructor team. Do you have his contact?

**Comment by jevanilla** [comment]
Filipe it's jevanilla. Hasn't changed since last year.
