### ISSUE TITLE
Helper guide

### ISSUE THREAD

**Issue by leewujung** [oceanhackweek/ohw-tutorials#70]
From tutorial team:

Helpers are the central part of tutorials!
@oceanhackweek/ohw22-mentor-helper-presenter  please consider being "helper" in some capacity during the event!
Below is a brief helper guide.

Please do:
- Make sure to follow Code of Conduct in interacting on slack
- A question is asked 
  - if you know the answer, please answer it 
  - if you know partially the answer, please also answer, and ping someone who may know the answer
  - if no answers show up after some time, ping someone who may know the answer
- We will keep a few breakout rooms open on Zoom, feel free to move there to answer questions in detail/resolve problems
- Vote up the questions they want the moderator to push to instructor (also make sure to let participants know that)

**Comment by ocefpaf** [comment]
@douglasnehme, @nilodna, and @LuizaPS please let us know the teams you want to be added to. I'm guessing python and git?

**Comment by douglasnehme** [comment]
@ocefpaf I want to be added just to the python team. I will post it at [Helper user groups on Slack #71](https://github.com/oceanhackweek/ohw-tutorials/issues/71) issues now

**Comment by nilodna** [comment]
Hi @ocefpaf, I just posted at the https://github.com/oceanhackweek/ohw-tutorials/issues/71 issue where I can provide some help (and yes, my preferences are python and git).
