### ISSUE TITLE
Helper user groups on Slack

### ISSUE THREAD

**Issue by leewujung** [oceanhackweek/ohw-tutorials#71]
From tutorial team:

Here are the helper user groups we have on Slack that can be pinged easily to folks to ask for help.

@oceanhackweek/ohw22-mentor-helper-presenter :
Please check this initial list and comment in this thread **with your Slack username** so we can add/remove you to the helper group. Thanks!

- R helpers (@help-r): @btupper
- Python helpers (@help-python): @abkfenris @dgumustel @emiliom
- Git (@help-git): @lidefi87 @dgumustel @leewujung @ocefpaf @gmanuch
- ML helpers (@help-ml): @dgumustel @leewujung @ocefpaf @gmanuch @valentina-s 
- Infrastructure (@help-infrastructure): @ocefpaf @abkfenris @paigem

**Comment by emiliom** [comment]
You can add my name to @help-infrastructure

And FYI that list of Slack helper user groups is described and presented on our OHW22 web site, here:
https://oceanhackweek.github.io/resources/logistics/getting_help.html#slack-help-groups

**Comment by wkumler** [comment]
You can add me to the help-r group!

**Comment by lidefi87** [comment]
I am also able to provide R help if you need an extra person

**Comment by douglasnehme** [comment]
You can add me to @help-python team.

**Comment by nilodna** [comment]
Add me to the @help-python and @help-git teams, please.

**Comment by zacharykerickson** [comment]
Happy to be added to the @help-python team

**Comment by cathmmitchell** [comment]
Add me to the @help-python and @help-r teams

**Comment by leewujung** [comment]
> And FYI that list of Slack helper user groups is described and presented on our OHW22 web site, here:
> https://oceanhackweek.github.io/resources/logistics/getting_help.html#slack-help-groups

@emiliom : Could you add the 2 new user groups: @help-ml and @help-git? Thanks!

**Comment by ocefpaf** [comment]
I've added everybody above to the places where they manifest they can help. Please let me know if you made into the team. (Not sure if slack sends a note or something.)

> Could you add the 2 new user groups: @help-ml and @help-git? Thanks!

The help-git already exists on slack. I can create the help-ml now. Who should I add besides Valentina and myself?

PS: do we have git groups/team that correspond to the slack teams?

**Comment by abkfenris** [comment]
We don't have them right now for the `@help-` groups, just some of the task groups. https://github.com/orgs/oceanhackweek/teams

**Comment by leewujung** [comment]
@ocefpaf : I was referring to adding this info to the website in that message to @emiliom -- sorry for the confusion!
Also: I created these user groups on Slack when I posted this issue, with the people in the top comment added, so they already exist.

**Comment by jevanilla** [comment]
@leewujung are these private channels? I can't find any of them to join...

**Comment by leewujung** [comment]
@jevanilla: These are slack user groups, and I think only owners/admins can add people to that. 
Please respond to this thread so we can add you in the groups!

**Comment by jevanilla** [comment]
@leewujung Please add me to the r and ML groups

**Comment by abkfenris** [comment]
In the past we tried to have multiple different channels for help by topic, but it was hard to get participants to make it to the right channel for their topic. By using Slack user groups, we can minimize the amount of confusion and cross posting trying to find help.

Instead we can direct everyone to the `#ohw22-helpdesk` channel to ask questions. It would be great to have a schedule of folks directing traffic to the right user groups. 

This also allows us to page a group to a channel to answer a question in context, say if a project team gets themself in a bind.

**Comment by ocefpaf** [comment]
> @leewujung Please add me to the r and ML groups

Done!

**Comment by virginiagarciaalonso** [comment]
@leewujung you can add me to the @help-r group :)

**Comment by ocefpaf** [comment]
> @leewujung you can add me to the @help-r group :)

Done!

Folks, if you do not have the same username on GitHub and slack you really help me out if you spell them out here. Sometimes looking for first/last names can lead to ambiguities b/c our gh and slack goes back to 2018 events and tons of people!

**Comment by emiliom** [comment]
> @emiliom : Could you add the 2 new user groups to the website: @help-ml and @help-git? Thanks!

Done and live: https://oceanhackweek.github.io/resources/logistics/getting_help.html#slack-help-groups

**Comment by dbrisaro** [comment]
You can add me to @help-python, thanks a lot!

**Comment by ocefpaf** [comment]
> You can add me to @help-python, thanks a lot!

@dbrisaro please see https://github.com/oceanhackweek/ohw-tutorials/issues/71#issuecomment-1208283459

**Comment by emiliom** [comment]
> I cannot find you on slack BTW. Do you need an invite?

She's on Slack (OHW20 alum). It's `@daniu`. Thanks

**Comment by ocefpaf** [comment]
Doing some housekeeping and closing issues. We probably don't need to keep this one open. Feel free to reopen if you disagree.
