### ISSUE TITLE
Data visualization in R

### ISSUE THREAD

**Issue by ocefpaf** [oceanhackweek/ohw-tutorials#79]
@cathmmitchell and @jevanilla this is the place for the R Viz tutorial materials: https://github.com/oceanhackweek/ohw-tutorials/tree/OHW22/02-Wed

**Comment by jevanilla** [comment]
@ocefpaf  This tutorial will be given by @chross22 (Camille Ross)

**Comment by jevanilla** [comment]
@ocefpaf The notebooks for this tutorial have been added in a pull request: https://github.com/oceanhackweek/ohw-tutorials/pull/92

**Comment by jevanilla** [comment]
@ocefpaf This tutorial is happening now. Can you please close this issue?
