### ISSUE TITLE
Best practices for reproducible research

### ISSUE THREAD

**Issue by ocefpaf** [oceanhackweek/ohw-tutorials#80]
@SeascapeScience we'll use your recording on Thursday but it would be nice to have the video on YouTube, if you can upload it, to make it easier to watch anywhere.

**Comment by SeascapeScience** [comment]
Sounds good. Is there a youtube channel associated with ohw or something like that I should be uploading to?

**Comment by ocefpaf** [comment]
> Sounds good. Is there a youtube channel associated with ohw or something like that I should be uploading to?

@leewujung I think I recall Jane mentioning something about this but I'm not sure. Do you know anything?

**Comment by leewujung** [comment]
Since Kyle will be helping us uploading everything, please shared the recording here: https://drive.google.com/drive/u/1/folders/1xsqwY2rtkrWa0EeH7jZYw1GjlsSn_s0Z
and then he could upload from there.

We are still waiting for eScience to give Kyle access to the Youtube channel.

**Comment by SeascapeScience** [comment]
Okay, sounds good.

**Comment by ocefpaf** [comment]
Closing this. Thanks @SeascapeScience for the awesome video!
