### ISSUE TITLE
Data visualization in Python materials

### ISSUE THREAD

**Issue by ocefpaf** [oceanhackweek/ohw-tutorials#82]
@dgumustel your notebooks and presentation materials should go into: https://github.com/oceanhackweek/ohw-tutorials/tree/OHW22/02-Wed

Be sure to test them in the Hub to confirm that everything works. Let me know if you need anything!

**Comment by dgumustel** [comment]
@ocefpaf Notebooks ran smoothly on the Hub, my PR is in!

**Comment by ocefpaf** [comment]
Solved in #85. Thanks @dgumustel!
